-- Migration: Knowledge Map tables
-- Run this in the Supabase SQL editor against the existing database.

-- Enable pgvector extension (needed for embeddings)
create extension if not exists vector;

-- Add embedding column to submissions
alter table submissions add column if not exists embedding vector(1024);

-- Submission tags (auto-generated by LLM)
create table if not exists submission_tags (
  id uuid default gen_random_uuid() primary key,
  submission_id uuid references submissions(id) on delete cascade,
  tag text not null,
  confidence float,
  created_at timestamptz default now()
);

-- Projection cache (UMAP 2D coordinates, recomputed per cycle)
create table if not exists projection_cache (
  id uuid default gen_random_uuid() primary key,
  submission_id uuid references submissions(id) on delete cascade,
  x float not null,
  y float not null,
  cluster_id integer,
  computed_at timestamptz default now()
);

-- Cluster labels (auto-generated theme summaries)
create table if not exists cluster_labels (
  id uuid default gen_random_uuid() primary key,
  cluster_id integer not null,
  label text not null,
  representative_submission_ids uuid[],
  computed_at timestamptz default now()
);

-- Map interactions (researcher feedback on the map)
create table if not exists map_interactions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id),
  interaction_type text not null check (interaction_type in ('flag_connection', 'dispute_placement', 'seed_convergence')),
  payload jsonb,
  created_at timestamptz default now()
);

-- Indexes
create index if not exists idx_projection_cache_submission on projection_cache (submission_id);
create index if not exists idx_projection_cache_cluster on projection_cache (cluster_id);
create index if not exists idx_submission_tags_tag on submission_tags (tag);
create index if not exists idx_submission_tags_submission on submission_tags (submission_id);

-- RPC function for nearest neighbor search via pgvector
create or replace function match_submissions(
  query_embedding vector(1024),
  match_count int default 5
)
returns table (
  id uuid,
  title text,
  body text,
  name text,
  distance float
)
language sql stable
as $$
  select
    s.id,
    s.title,
    s.body,
    p.name,
    (s.embedding <=> query_embedding)::float as distance
  from submissions s
  join profiles p on p.id = s.profile_id
  where s.embedding is not null
  order by s.embedding <=> query_embedding
  limit match_count;
$$;
